import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Ignite Shop',
    default: 'Shop',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased bg-gray-900 text-gray-100`}>{children}</body>
    </html>
  )
}
