import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import logo from '@/public/assets/logo.svg'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Ignite Shop',
    default: 'Shop',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased bg-gray-900 text-gray-100 flex flex-col justify-center min-h-screen`}>
        <header className='w-full pb-8 pt-2 max-w-[1180px] mx-auto'>
          <Image src={logo} width={129.74} height={52} alt='logo da loja' />
        </header>
        {children}
        </body>
    </html>
  )
}
